// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMMYjZ73TQfuaAPlPR6szmUuBtKWj427k',
    appId: '1:642981350479:web:706c779386a6b79b086e3a',
    messagingSenderId: '642981350479',
    projectId: 'internpractice1',
    authDomain: 'internpractice1.firebaseapp.com',
    databaseURL: 'https://internpractice1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internpractice1.firebasestorage.app',
    measurementId: 'G-PBFP364DQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPAG7FCCa6lLeQdISAgU7Dv5TBQs3nwVQ',
    appId: '1:642981350479:android:0435ef20ead67f7e086e3a',
    messagingSenderId: '642981350479',
    projectId: 'internpractice1',
    databaseURL: 'https://internpractice1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internpractice1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTGhp8q4J4bO0_As8wqcHwHSg7VPiHAT4',
    appId: '1:642981350479:ios:76b60066f5f2f208086e3a',
    messagingSenderId: '642981350479',
    projectId: 'internpractice1',
    databaseURL: 'https://internpractice1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internpractice1.firebasestorage.app',
    iosBundleId: 'com.example.aunproject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTGhp8q4J4bO0_As8wqcHwHSg7VPiHAT4',
    appId: '1:642981350479:ios:76b60066f5f2f208086e3a',
    messagingSenderId: '642981350479',
    projectId: 'internpractice1',
    databaseURL: 'https://internpractice1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internpractice1.firebasestorage.app',
    iosBundleId: 'com.example.aunproject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMMYjZ73TQfuaAPlPR6szmUuBtKWj427k',
    appId: '1:642981350479:web:09fe4b6c66b20dd7086e3a',
    messagingSenderId: '642981350479',
    projectId: 'internpractice1',
    authDomain: 'internpractice1.firebaseapp.com',
    databaseURL: 'https://internpractice1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'internpractice1.firebasestorage.app',
    measurementId: 'G-J3RD56045W',
  );

}